# Generated by Django 4.2.2 on 2023-06-30 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_customuser_pka_customuser_ska'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raffle_date', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='santa_raffle.event')),
                ('giftee_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftee', to=settings.AUTH_USER_MODEL)),
                ('giftee_pka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftee_pka', to='accounts.cryptokey')),
                ('gifter_pka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_pka', to='accounts.cryptokey')),
                ('gifter_prk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_prk', to='accounts.cryptokey')),
                ('gifter_srk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_srk', to='accounts.cryptokey')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='members', through='santa_raffle.Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='pkey_list',
            field=models.ManyToManyField(to='accounts.cryptokey'),
        ),
    ]
