# Generated by Django 4.2.2 on 2023-06-27 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import santa_raffle.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BinaryField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raffle_date', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(default=santa_raffle.models.Event.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='santa_raffle.event')),
                ('giftee_id', models.OneToOneField(default=django.db.models.deletion.SET_DEFAULT, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='giftee', to=settings.AUTH_USER_MODEL)),
                ('giftee_pka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftee_pka', to='santa_raffle.cryptokey')),
                ('gifter_pka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_pka', to='santa_raffle.cryptokey')),
                ('gifter_prk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_prk', to='santa_raffle.cryptokey')),
                ('gifter_srk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_srk', to='santa_raffle.cryptokey')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='members', through='santa_raffle.Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=django.db.models.deletion.SET_DEFAULT, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
