# Generated by Django 4.2.2 on 2023-06-24 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import santa_raffle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BinaryField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.TextField(blank=True, null=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pka', to='santa_raffle.cryptokey')),
                ('ska', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ska', to='santa_raffle.cryptokey')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftee_id', models.OneToOneField(default=santa_raffle.models.User.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='giftee', to='santa_raffle.user')),
                ('giftee_pka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftee_pka', to='santa_raffle.cryptokey')),
                ('gifter_pka', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_pka', to='santa_raffle.cryptokey')),
                ('gifter_prk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_prk', to='santa_raffle.cryptokey')),
                ('gifter_srk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_srk', to='santa_raffle.cryptokey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='santa_raffle.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raffle_date', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default=santa_raffle.models.User.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to='santa_raffle.user')),
                ('members', models.ManyToManyField(related_name='members', to='santa_raffle.user')),
                ('pkey_list', models.ManyToManyField(to='santa_raffle.user')),
            ],
        ),
    ]
