# Generated by Django 4.2.2 on 2023-06-28 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('santa_raffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='pkey_list',
            field=models.ManyToManyField(to='santa_raffle.cryptokey'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='santa_raffle.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='giftee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftee', to=settings.AUTH_USER_MODEL),
        ),
    ]
