# Generated by Django 4.2.2 on 2023-06-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cryptokey_customuser_likes'),
        ('santa_raffle', '0002_remove_event_organizer_event_pkey_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pkey_list',
            field=models.ManyToManyField(to='accounts.cryptokey'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='giftee_pka',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftee_pka', to='accounts.cryptokey'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gifter_pka',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_pka', to='accounts.cryptokey'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gifter_prk',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_prk', to='accounts.cryptokey'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gifter_srk',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter_srk', to='accounts.cryptokey'),
        ),
        migrations.DeleteModel(
            name='CryptoKey',
        ),
    ]
