# Generated by Django 4.2.2 on 2023-07-12 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('santa_raffle', '0006_alter_event_members_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
