# Generated by Django 4.2.2 on 2023-07-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santa_raffle', '0008_remove_event_members_event_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santa_raffle.event'),
        ),
    ]
