# Generated by Django 4.2.2 on 2023-07-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_raffle', '0010_remove_event_members_remove_participant_giftee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='giftee_data',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
