# Generated by Django 4.2.2 on 2023-07-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_raffle', '0013_alter_event_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='giftee_data',
        ),
        migrations.AddField(
            model_name='participant',
            name='giftee_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='giftee_pka',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='gifter_pka',
            field=models.TextField(blank=True),
        ),
    ]
