# Generated by Django 4.2.2 on 2023-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_raffle', '0014_remove_participant_giftee_data_participant_giftee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='event_key',
            field=models.TextField(blank=True),
        ),
    ]
