# Generated by Django 4.2.2 on 2023-07-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_raffle', '0015_participant_event_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='giftee_pka',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='gifter_pka',
        ),
        migrations.AddField(
            model_name='participant',
            name='giftee_chat_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='participant',
            name='giftee_chat_key',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='participant',
            name='gifter_chat_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='participant',
            name='gifter_chat_key',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
