# Generated by Django 4.2.2 on 2023-06-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cryptokey_customuser_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptokey',
            name='key_status',
            field=models.CharField(choices=[(1, 'Anon'), (2, 'Known')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cryptokey',
            name='key_type',
            field=models.CharField(choices=[(1, 'Public'), (2, 'Private')], max_length=1, null=True),
        ),
    ]
