# Generated by Django 4.2.2 on 2023-06-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cryptokey_key_status_cryptokey_key_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pka',
            field=models.OneToOneField(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pka', to='accounts.cryptokey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ska',
            field=models.OneToOneField(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ska', to='accounts.cryptokey'),
            preserve_default=False,
        ),
    ]
