# Generated by Django 4.2.2 on 2023-06-29 20:50

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_pka_customuser_ska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pka',
            field=models.OneToOneField(default=accounts.models.CryptoKey.generate_pka, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pka', to='accounts.cryptokey'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ska',
            field=models.OneToOneField(default=accounts.models.CryptoKey.generate_ska, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ska', to='accounts.cryptokey'),
        ),
    ]
