# Generated by Django 4.2.2 on 2023-07-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_pka_alter_customuser_ska'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pka',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ska',
        ),
    ]
