# Generated by Django 4.2.2 on 2023-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_pka_alter_customuser_ska'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptokey',
            name='key_status',
        ),
        migrations.RemoveField(
            model_name='cryptokey',
            name='key_type',
        ),
        migrations.AlterField(
            model_name='cryptokey',
            name='value',
            field=models.TextField(editable=False, max_length=200),
        ),
    ]
