# Generated by Django 4.2.2 on 2023-07-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_cryptokey_key_status_and_more'),
        ('accounts', '0006_remove_customuser_pka_remove_customuser_ska'),
    ]

    operations = [
    ]
