# Generated by Django 4.2.2 on 2023-07-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20230712_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptokey',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
