# Generated by Django 4.2.2 on 2023-07-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_cryptokey_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pubkey',
            field=models.TextField(blank=True),
        ),
    ]
